### PR TITLE
More Bluebird externs

### PR DESCRIPTION
**Pull request by simshanith**
For usage with `:optimizations :advanced` - allow fuller subset of `Bluebird` functionality

### CODE REVIEW

**Comment by simshanith** [comment]
Still missing some advanced `Bluebird` features, but most the basics covered in the [API Reference](http://bluebirdjs.com/docs/api-reference.html) are included

**Comment by simshanith** [comment]
Maybe worth considering moving all this https://github.com/cljsjs/packages

**Comment by niwinz** [comment]
Firstly thanks for your time and your efforts.

I have some questions/observations around your PR:
- Are you using interop for access all that methods. As fas as I understand, `noConflict` is used just for avoid bluebird promise leakage in the global context (https://github.com/funcool/promesa/blob/master/src/promesa/core.cljc#L43). Bluebird is intended to be a implementation detail.
- As you can observe in issues, I have a possible plan that replaces buluebird with more simple and more performant implementation.
- About cljsjs/packages, I'm not pretty interested because I don't like a big monolithic repository with all packages.

I will merge your changes because they are pretty nice and thanks, but take care that bluebird is just a implementation detail, so in future it can be replaced by other thing.

**Comment by simshanith** [comment]
Re: interop - yes. In a `cljs`-specific source file, I may want specific underlying Bluebird functionality.

Could simplify the implementation of certain abstractions, e.g. node-style callbacks with the error first (#13).

I would advise interop be abstracted sufficiently as a utility instead of requiring interop in application code, but the externs allow a fuller subset of Bluebird abstractions. If the underlying Promise implementation is swapped, cross-platform `cljc` can recreate the abstractions from Bluebird as desired.

Re: cljs/packages - each set of externs is published as its own Clojars package, but I agree, the monolithic repository leaves much to be desired. However, whatever Promise library could be a cljsjs package and be consumed by other projects more easily.

Thanks for the merge, and feedback!

**Comment by niwinz** [comment]
I will deploy a new release surely today with your changes ;)

**Pull request merged**
