### PR TITLE
Add syntax validation to `p/let`

### PR DESCRIPTION
**Pull request by frenchy64**
The CI is failing because the recent AAtom implementation was not committed to git.

### CODE REVIEW

**Comment by niwinz** [comment]
Yep, I have removed the async_atom tests, I have experimented a bit but on the end I don't go to add it.

**Comment by niwinz** [comment]
Is this ready?, can you put all this in a single commit? (I can do it myself but I need to confirm if this is ready)

**Comment by frenchy64** [comment]
Yes, it's ready, go ahead.

-------- Original Message --------

**Comment by niwinz** [comment]
merged using command line :heart: thanks

**Pull request closed without merging**
