### PR TITLE
Setup clj-kondo config

### PR DESCRIPTION
**Pull request by wilkerlucio**
This change will add support out of the box for linting with clj-kondo.

### CODE REVIEW

**Comment by niwinz** [comment]
Nice!
I suppose it will require a release for make it available to everybody?

**Comment by wilkerlucio** [comment]
Yes, requires a release, so people can use `clj-kondo --copy-configs` to get settings for promesa (and any other lib that provides kondo exports).

**Comment by niwinz** [comment]
ack, I will bump a new release ASAP

**Comment by wilkerlucio** [comment]
Awesome! I just tested it and works as expected in the latest version.

**Pull request merged**
