### PR TITLE
JVM reify cleanup for GraalVM

### PR DESCRIPTION
**Pull request by k13gomez**
Refactor callback functions and scheduled task function implementation to use concrete type implementations instead of reify'd implementation.

### CODE REVIEW

**Comment by k13gomez** [comment]
@niwinz this is what I had in mind for replacing `reify` in the JVM implementation with concrete type implementations.

**Comment by niwinz** [comment]
@k13gomez it's ok, so with this changes promesa compiles correctly with GraalVM?

**Comment by k13gomez** [comment]
@niwinz yeah, this compiles properly with GraalVM, below is some example code testing the changes:
- **project.clj**
```clojure
(defproject mynativeapp "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.0"]
                 [funcool/promesa "3.0.0-SNAPSHOT"]]
  :main ^:skip-aot mynativeapp.core
  :target-path "target/%s"
  :plugins [[io.taylorwood/lein-native-image "0.3.1"]]
  :native-image {:opts ["-Dclojure.compiler.direct-linking=true"
                        "--initialize-at-build-time"
                        "--no-server"
                        "--verbose"]}
  :profiles {:uberjar {:aot :all}})
```
- **core.clj**
```clojure
core.clj
(ns mynativeapp.core
  (:require [promesa.core :as p])
  (:import [java.util.concurrent CompletableFuture])
  (:gen-class))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (let [success-prom (p/promise (fn [resolve reject]
                                  (resolve "test success")))
        failure-prom (p/promise (fn [resolve reject]
                                  (reject (ex-info "test failure" {}))))]
    @(p/schedule 1000
                 (fn []
                   @(p/then success-prom println)
                   @(p/catch failure-prom println)))
    (shutdown-agents)
    (System/exit 0)))
```

**Comment by niwinz** [comment]
Nice!

PD: new snapshot is bumped.

**Pull request merged**
